version: '3'
services:
  dockerflaskapp:
    build:
      context: .
      dockerfile: Dockerfile-flask
    container_name: dockerflaskapp
    ports: 
      - 5000:5000
    networks:
      - host
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - FLASK_DEBUG=1
      - FLASK_APP=./app.py
    volumes:
      ['./app:/app']

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - host
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=DBLP

  mongo-seed:
        env_file:
            - .env
        build:
            context: ./mongo_seed
            dockerfile: Dockerfile
            args:
                - DATABASE_URI=$DATABASE_URI
                - USERNAME=$MONGO_INITDB_ROOT_USERNAME
                - PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
        depends_on:
            - mongo
        networks:
            - host
    

networks:
    host: